# Site settings
author: John Lemaster
title: Lemaster's DS
header-img: img/home-bg.png
email: heylemaster@gmail.com
copyright_name: John Lemaster
description: > # this means to ignore newlines until "baseurl:"
  Lemaster's DS
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lemaster1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
